#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dienthoai.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="qldienthoai")]
	public partial class DbqldienthoaiDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAdmin(Admin instance);
    partial void UpdateAdmin(Admin instance);
    partial void DeleteAdmin(Admin instance);
    partial void Insertchitiethoadon(chitiethoadon instance);
    partial void Updatechitiethoadon(chitiethoadon instance);
    partial void Deletechitiethoadon(chitiethoadon instance);
    partial void InsertHOADON(HOADON instance);
    partial void UpdateHOADON(HOADON instance);
    partial void DeleteHOADON(HOADON instance);
    partial void InsertKhachHang(KhachHang instance);
    partial void UpdateKhachHang(KhachHang instance);
    partial void DeleteKhachHang(KhachHang instance);
    partial void InsertKhuyenMai(KhuyenMai instance);
    partial void UpdateKhuyenMai(KhuyenMai instance);
    partial void DeleteKhuyenMai(KhuyenMai instance);
    partial void InsertLoaiadmin(Loaiadmin instance);
    partial void UpdateLoaiadmin(Loaiadmin instance);
    partial void DeleteLoaiadmin(Loaiadmin instance);
    partial void Insertloaisanpham(loaisanpham instance);
    partial void Updateloaisanpham(loaisanpham instance);
    partial void Deleteloaisanpham(loaisanpham instance);
    partial void Insertnhacungcap(nhacungcap instance);
    partial void Updatenhacungcap(nhacungcap instance);
    partial void Deletenhacungcap(nhacungcap instance);
    partial void Insertphieunhap(phieunhap instance);
    partial void Updatephieunhap(phieunhap instance);
    partial void Deletephieunhap(phieunhap instance);
    partial void Insertsanpham(sanpham instance);
    partial void Updatesanpham(sanpham instance);
    partial void Deletesanpham(sanpham instance);
    #endregion
		
		public DbqldienthoaiDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["qldienthoaiConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DbqldienthoaiDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbqldienthoaiDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbqldienthoaiDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbqldienthoaiDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Admin> Admins
		{
			get
			{
				return this.GetTable<Admin>();
			}
		}
		
		public System.Data.Linq.Table<chitiethoadon> chitiethoadons
		{
			get
			{
				return this.GetTable<chitiethoadon>();
			}
		}
		
		public System.Data.Linq.Table<HOADON> HOADONs
		{
			get
			{
				return this.GetTable<HOADON>();
			}
		}
		
		public System.Data.Linq.Table<KhachHang> KhachHangs
		{
			get
			{
				return this.GetTable<KhachHang>();
			}
		}
		
		public System.Data.Linq.Table<KhuyenMai> KhuyenMais
		{
			get
			{
				return this.GetTable<KhuyenMai>();
			}
		}
		
		public System.Data.Linq.Table<Loaiadmin> Loaiadmins
		{
			get
			{
				return this.GetTable<Loaiadmin>();
			}
		}
		
		public System.Data.Linq.Table<loaisanpham> loaisanphams
		{
			get
			{
				return this.GetTable<loaisanpham>();
			}
		}
		
		public System.Data.Linq.Table<nhacungcap> nhacungcaps
		{
			get
			{
				return this.GetTable<nhacungcap>();
			}
		}
		
		public System.Data.Linq.Table<phieunhap> phieunhaps
		{
			get
			{
				return this.GetTable<phieunhap>();
			}
		}
		
		public System.Data.Linq.Table<sanpham> sanphams
		{
			get
			{
				return this.GetTable<sanpham>();
			}
		}
		
		public System.Data.Linq.Table<taikhoan> taikhoans
		{
			get
			{
				return this.GetTable<taikhoan>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Admin")]
	public partial class Admin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Ma_Admin;
		
		private string _Ten_Admin;
		
		private string _Ma_Loai_Admin;
		
		private string _Dia_Chi;
		
		private string _SDT;
		
		private EntitySet<phieunhap> _phieunhaps;
		
		private EntityRef<Loaiadmin> _Loaiadmin;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_AdminChanging(string value);
    partial void OnMa_AdminChanged();
    partial void OnTen_AdminChanging(string value);
    partial void OnTen_AdminChanged();
    partial void OnMa_Loai_AdminChanging(string value);
    partial void OnMa_Loai_AdminChanged();
    partial void OnDia_ChiChanging(string value);
    partial void OnDia_ChiChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    #endregion
		
		public Admin()
		{
			this._phieunhaps = new EntitySet<phieunhap>(new Action<phieunhap>(this.attach_phieunhaps), new Action<phieunhap>(this.detach_phieunhaps));
			this._Loaiadmin = default(EntityRef<Loaiadmin>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_Admin", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Ma_Admin
		{
			get
			{
				return this._Ma_Admin;
			}
			set
			{
				if ((this._Ma_Admin != value))
				{
					this.OnMa_AdminChanging(value);
					this.SendPropertyChanging();
					this._Ma_Admin = value;
					this.SendPropertyChanged("Ma_Admin");
					this.OnMa_AdminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_Admin", DbType="NVarChar(30)")]
		public string Ten_Admin
		{
			get
			{
				return this._Ten_Admin;
			}
			set
			{
				if ((this._Ten_Admin != value))
				{
					this.OnTen_AdminChanging(value);
					this.SendPropertyChanging();
					this._Ten_Admin = value;
					this.SendPropertyChanged("Ten_Admin");
					this.OnTen_AdminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_Loai_Admin", DbType="VarChar(10)")]
		public string Ma_Loai_Admin
		{
			get
			{
				return this._Ma_Loai_Admin;
			}
			set
			{
				if ((this._Ma_Loai_Admin != value))
				{
					if (this._Loaiadmin.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMa_Loai_AdminChanging(value);
					this.SendPropertyChanging();
					this._Ma_Loai_Admin = value;
					this.SendPropertyChanged("Ma_Loai_Admin");
					this.OnMa_Loai_AdminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dia_Chi", DbType="NVarChar(70)")]
		public string Dia_Chi
		{
			get
			{
				return this._Dia_Chi;
			}
			set
			{
				if ((this._Dia_Chi != value))
				{
					this.OnDia_ChiChanging(value);
					this.SendPropertyChanging();
					this._Dia_Chi = value;
					this.SendPropertyChanged("Dia_Chi");
					this.OnDia_ChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(10)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Admin_phieunhap", Storage="_phieunhaps", ThisKey="Ma_Admin", OtherKey="Ma_Admin")]
		public EntitySet<phieunhap> phieunhaps
		{
			get
			{
				return this._phieunhaps;
			}
			set
			{
				this._phieunhaps.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Loaiadmin_Admin", Storage="_Loaiadmin", ThisKey="Ma_Loai_Admin", OtherKey="Ma_Loai_Admin", IsForeignKey=true)]
		public Loaiadmin Loaiadmin
		{
			get
			{
				return this._Loaiadmin.Entity;
			}
			set
			{
				Loaiadmin previousValue = this._Loaiadmin.Entity;
				if (((previousValue != value) 
							|| (this._Loaiadmin.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Loaiadmin.Entity = null;
						previousValue.Admins.Remove(this);
					}
					this._Loaiadmin.Entity = value;
					if ((value != null))
					{
						value.Admins.Add(this);
						this._Ma_Loai_Admin = value.Ma_Loai_Admin;
					}
					else
					{
						this._Ma_Loai_Admin = default(string);
					}
					this.SendPropertyChanged("Loaiadmin");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_phieunhaps(phieunhap entity)
		{
			this.SendPropertyChanging();
			entity.Admin = this;
		}
		
		private void detach_phieunhaps(phieunhap entity)
		{
			this.SendPropertyChanging();
			entity.Admin = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.chitiethoadon")]
	public partial class chitiethoadon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Ma_HD;
		
		private int _Ma_SP;
		
		private System.Nullable<byte> _So_Luong;
		
		private string _Don_Gia;
		
		private EntityRef<sanpham> _sanpham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_HDChanging(string value);
    partial void OnMa_HDChanged();
    partial void OnMa_SPChanging(int value);
    partial void OnMa_SPChanged();
    partial void OnSo_LuongChanging(System.Nullable<byte> value);
    partial void OnSo_LuongChanged();
    partial void OnDon_GiaChanging(string value);
    partial void OnDon_GiaChanged();
    #endregion
		
		public chitiethoadon()
		{
			this._sanpham = default(EntityRef<sanpham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_HD", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Ma_HD
		{
			get
			{
				return this._Ma_HD;
			}
			set
			{
				if ((this._Ma_HD != value))
				{
					this.OnMa_HDChanging(value);
					this.SendPropertyChanging();
					this._Ma_HD = value;
					this.SendPropertyChanged("Ma_HD");
					this.OnMa_HDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_SP", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Ma_SP
		{
			get
			{
				return this._Ma_SP;
			}
			set
			{
				if ((this._Ma_SP != value))
				{
					if (this._sanpham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMa_SPChanging(value);
					this.SendPropertyChanging();
					this._Ma_SP = value;
					this.SendPropertyChanged("Ma_SP");
					this.OnMa_SPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_So_Luong", DbType="TinyInt")]
		public System.Nullable<byte> So_Luong
		{
			get
			{
				return this._So_Luong;
			}
			set
			{
				if ((this._So_Luong != value))
				{
					this.OnSo_LuongChanging(value);
					this.SendPropertyChanging();
					this._So_Luong = value;
					this.SendPropertyChanged("So_Luong");
					this.OnSo_LuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Don_Gia", DbType="VarChar(10)")]
		public string Don_Gia
		{
			get
			{
				return this._Don_Gia;
			}
			set
			{
				if ((this._Don_Gia != value))
				{
					this.OnDon_GiaChanging(value);
					this.SendPropertyChanging();
					this._Don_Gia = value;
					this.SendPropertyChanged("Don_Gia");
					this.OnDon_GiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="sanpham_chitiethoadon", Storage="_sanpham", ThisKey="Ma_SP", OtherKey="Ma_SP", IsForeignKey=true)]
		public sanpham sanpham
		{
			get
			{
				return this._sanpham.Entity;
			}
			set
			{
				sanpham previousValue = this._sanpham.Entity;
				if (((previousValue != value) 
							|| (this._sanpham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._sanpham.Entity = null;
						previousValue.chitiethoadons.Remove(this);
					}
					this._sanpham.Entity = value;
					if ((value != null))
					{
						value.chitiethoadons.Add(this);
						this._Ma_SP = value.Ma_SP;
					}
					else
					{
						this._Ma_SP = default(int);
					}
					this.SendPropertyChanged("sanpham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HOADON")]
	public partial class HOADON : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Ma_HD;
		
		private System.Nullable<int> _Ma_KH;
		
		private string _Ma_KM;
		
		private System.Nullable<System.DateTime> _Ngay_Lap;
		
		private System.Nullable<System.DateTime> _Ngay_Giao_Hang;
		
		private EntityRef<KhachHang> _KhachHang;
		
		private EntityRef<KhuyenMai> _KhuyenMai;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_HDChanging(string value);
    partial void OnMa_HDChanged();
    partial void OnMa_KHChanging(System.Nullable<int> value);
    partial void OnMa_KHChanged();
    partial void OnMa_KMChanging(string value);
    partial void OnMa_KMChanged();
    partial void OnNgay_LapChanging(System.Nullable<System.DateTime> value);
    partial void OnNgay_LapChanged();
    partial void OnNgay_Giao_HangChanging(System.Nullable<System.DateTime> value);
    partial void OnNgay_Giao_HangChanged();
    #endregion
		
		public HOADON()
		{
			this._KhachHang = default(EntityRef<KhachHang>);
			this._KhuyenMai = default(EntityRef<KhuyenMai>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_HD", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Ma_HD
		{
			get
			{
				return this._Ma_HD;
			}
			set
			{
				if ((this._Ma_HD != value))
				{
					this.OnMa_HDChanging(value);
					this.SendPropertyChanging();
					this._Ma_HD = value;
					this.SendPropertyChanged("Ma_HD");
					this.OnMa_HDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_KH", DbType="Int")]
		public System.Nullable<int> Ma_KH
		{
			get
			{
				return this._Ma_KH;
			}
			set
			{
				if ((this._Ma_KH != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMa_KHChanging(value);
					this.SendPropertyChanging();
					this._Ma_KH = value;
					this.SendPropertyChanged("Ma_KH");
					this.OnMa_KHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_KM", DbType="VarChar(10)")]
		public string Ma_KM
		{
			get
			{
				return this._Ma_KM;
			}
			set
			{
				if ((this._Ma_KM != value))
				{
					if (this._KhuyenMai.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMa_KMChanging(value);
					this.SendPropertyChanging();
					this._Ma_KM = value;
					this.SendPropertyChanged("Ma_KM");
					this.OnMa_KMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngay_Lap", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngay_Lap
		{
			get
			{
				return this._Ngay_Lap;
			}
			set
			{
				if ((this._Ngay_Lap != value))
				{
					this.OnNgay_LapChanging(value);
					this.SendPropertyChanging();
					this._Ngay_Lap = value;
					this.SendPropertyChanged("Ngay_Lap");
					this.OnNgay_LapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngay_Giao_Hang", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngay_Giao_Hang
		{
			get
			{
				return this._Ngay_Giao_Hang;
			}
			set
			{
				if ((this._Ngay_Giao_Hang != value))
				{
					this.OnNgay_Giao_HangChanging(value);
					this.SendPropertyChanging();
					this._Ngay_Giao_Hang = value;
					this.SendPropertyChanged("Ngay_Giao_Hang");
					this.OnNgay_Giao_HangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_HOADON", Storage="_KhachHang", ThisKey="Ma_KH", OtherKey="Ma_KH", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.HOADONs.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.HOADONs.Add(this);
						this._Ma_KH = value.Ma_KH;
					}
					else
					{
						this._Ma_KH = default(Nullable<int>);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhuyenMai_HOADON", Storage="_KhuyenMai", ThisKey="Ma_KM", OtherKey="Ma_KM", IsForeignKey=true)]
		public KhuyenMai KhuyenMai
		{
			get
			{
				return this._KhuyenMai.Entity;
			}
			set
			{
				KhuyenMai previousValue = this._KhuyenMai.Entity;
				if (((previousValue != value) 
							|| (this._KhuyenMai.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhuyenMai.Entity = null;
						previousValue.HOADONs.Remove(this);
					}
					this._KhuyenMai.Entity = value;
					if ((value != null))
					{
						value.HOADONs.Add(this);
						this._Ma_KM = value.Ma_KM;
					}
					else
					{
						this._Ma_KM = default(string);
					}
					this.SendPropertyChanged("KhuyenMai");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhachHang")]
	public partial class KhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Ma_KH;
		
		private string _Ten_KH;
		
		private string _Dia_Chi;
		
		private string _SDT;
		
		private string _Ten_DangNhapKH;
		
		private string _Matkhau;
		
		private string _Email_KH;
		
		private EntitySet<HOADON> _HOADONs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_KHChanging(int value);
    partial void OnMa_KHChanged();
    partial void OnTen_KHChanging(string value);
    partial void OnTen_KHChanged();
    partial void OnDia_ChiChanging(string value);
    partial void OnDia_ChiChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnTen_DangNhapKHChanging(string value);
    partial void OnTen_DangNhapKHChanged();
    partial void OnMatkhauChanging(string value);
    partial void OnMatkhauChanged();
    partial void OnEmail_KHChanging(string value);
    partial void OnEmail_KHChanged();
    #endregion
		
		public KhachHang()
		{
			this._HOADONs = new EntitySet<HOADON>(new Action<HOADON>(this.attach_HOADONs), new Action<HOADON>(this.detach_HOADONs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_KH", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Ma_KH
		{
			get
			{
				return this._Ma_KH;
			}
			set
			{
				if ((this._Ma_KH != value))
				{
					this.OnMa_KHChanging(value);
					this.SendPropertyChanging();
					this._Ma_KH = value;
					this.SendPropertyChanged("Ma_KH");
					this.OnMa_KHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_KH", DbType="NVarChar(30)")]
		public string Ten_KH
		{
			get
			{
				return this._Ten_KH;
			}
			set
			{
				if ((this._Ten_KH != value))
				{
					this.OnTen_KHChanging(value);
					this.SendPropertyChanging();
					this._Ten_KH = value;
					this.SendPropertyChanged("Ten_KH");
					this.OnTen_KHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dia_Chi", DbType="NVarChar(70)")]
		public string Dia_Chi
		{
			get
			{
				return this._Dia_Chi;
			}
			set
			{
				if ((this._Dia_Chi != value))
				{
					this.OnDia_ChiChanging(value);
					this.SendPropertyChanging();
					this._Dia_Chi = value;
					this.SendPropertyChanged("Dia_Chi");
					this.OnDia_ChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(10)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_DangNhapKH", DbType="VarChar(25)")]
		public string Ten_DangNhapKH
		{
			get
			{
				return this._Ten_DangNhapKH;
			}
			set
			{
				if ((this._Ten_DangNhapKH != value))
				{
					this.OnTen_DangNhapKHChanging(value);
					this.SendPropertyChanging();
					this._Ten_DangNhapKH = value;
					this.SendPropertyChanged("Ten_DangNhapKH");
					this.OnTen_DangNhapKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matkhau", DbType="VarChar(25)")]
		public string Matkhau
		{
			get
			{
				return this._Matkhau;
			}
			set
			{
				if ((this._Matkhau != value))
				{
					this.OnMatkhauChanging(value);
					this.SendPropertyChanging();
					this._Matkhau = value;
					this.SendPropertyChanged("Matkhau");
					this.OnMatkhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email_KH", DbType="VarChar(25)")]
		public string Email_KH
		{
			get
			{
				return this._Email_KH;
			}
			set
			{
				if ((this._Email_KH != value))
				{
					this.OnEmail_KHChanging(value);
					this.SendPropertyChanging();
					this._Email_KH = value;
					this.SendPropertyChanged("Email_KH");
					this.OnEmail_KHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_HOADON", Storage="_HOADONs", ThisKey="Ma_KH", OtherKey="Ma_KH")]
		public EntitySet<HOADON> HOADONs
		{
			get
			{
				return this._HOADONs;
			}
			set
			{
				this._HOADONs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HOADONs(HOADON entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_HOADONs(HOADON entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhuyenMai")]
	public partial class KhuyenMai : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Ma_KM;
		
		private string _Ten_KM;
		
		private System.Nullable<System.DateTime> _Ngay_BD;
		
		private System.Nullable<System.DateTime> _Ngay_KT;
		
		private string _Phan_Tram_KM;
		
		private EntitySet<HOADON> _HOADONs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_KMChanging(string value);
    partial void OnMa_KMChanged();
    partial void OnTen_KMChanging(string value);
    partial void OnTen_KMChanged();
    partial void OnNgay_BDChanging(System.Nullable<System.DateTime> value);
    partial void OnNgay_BDChanged();
    partial void OnNgay_KTChanging(System.Nullable<System.DateTime> value);
    partial void OnNgay_KTChanged();
    partial void OnPhan_Tram_KMChanging(string value);
    partial void OnPhan_Tram_KMChanged();
    #endregion
		
		public KhuyenMai()
		{
			this._HOADONs = new EntitySet<HOADON>(new Action<HOADON>(this.attach_HOADONs), new Action<HOADON>(this.detach_HOADONs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_KM", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Ma_KM
		{
			get
			{
				return this._Ma_KM;
			}
			set
			{
				if ((this._Ma_KM != value))
				{
					this.OnMa_KMChanging(value);
					this.SendPropertyChanging();
					this._Ma_KM = value;
					this.SendPropertyChanged("Ma_KM");
					this.OnMa_KMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_KM", DbType="NVarChar(50)")]
		public string Ten_KM
		{
			get
			{
				return this._Ten_KM;
			}
			set
			{
				if ((this._Ten_KM != value))
				{
					this.OnTen_KMChanging(value);
					this.SendPropertyChanging();
					this._Ten_KM = value;
					this.SendPropertyChanged("Ten_KM");
					this.OnTen_KMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngay_BD", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngay_BD
		{
			get
			{
				return this._Ngay_BD;
			}
			set
			{
				if ((this._Ngay_BD != value))
				{
					this.OnNgay_BDChanging(value);
					this.SendPropertyChanging();
					this._Ngay_BD = value;
					this.SendPropertyChanged("Ngay_BD");
					this.OnNgay_BDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngay_KT", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngay_KT
		{
			get
			{
				return this._Ngay_KT;
			}
			set
			{
				if ((this._Ngay_KT != value))
				{
					this.OnNgay_KTChanging(value);
					this.SendPropertyChanging();
					this._Ngay_KT = value;
					this.SendPropertyChanged("Ngay_KT");
					this.OnNgay_KTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phan_Tram_KM", DbType="VarChar(5)")]
		public string Phan_Tram_KM
		{
			get
			{
				return this._Phan_Tram_KM;
			}
			set
			{
				if ((this._Phan_Tram_KM != value))
				{
					this.OnPhan_Tram_KMChanging(value);
					this.SendPropertyChanging();
					this._Phan_Tram_KM = value;
					this.SendPropertyChanged("Phan_Tram_KM");
					this.OnPhan_Tram_KMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhuyenMai_HOADON", Storage="_HOADONs", ThisKey="Ma_KM", OtherKey="Ma_KM")]
		public EntitySet<HOADON> HOADONs
		{
			get
			{
				return this._HOADONs;
			}
			set
			{
				this._HOADONs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HOADONs(HOADON entity)
		{
			this.SendPropertyChanging();
			entity.KhuyenMai = this;
		}
		
		private void detach_HOADONs(HOADON entity)
		{
			this.SendPropertyChanging();
			entity.KhuyenMai = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Loaiadmin")]
	public partial class Loaiadmin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Ma_Loai_Admin;
		
		private string _Ten_Loai;
		
		private EntitySet<Admin> _Admins;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_Loai_AdminChanging(string value);
    partial void OnMa_Loai_AdminChanged();
    partial void OnTen_LoaiChanging(string value);
    partial void OnTen_LoaiChanged();
    #endregion
		
		public Loaiadmin()
		{
			this._Admins = new EntitySet<Admin>(new Action<Admin>(this.attach_Admins), new Action<Admin>(this.detach_Admins));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_Loai_Admin", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Ma_Loai_Admin
		{
			get
			{
				return this._Ma_Loai_Admin;
			}
			set
			{
				if ((this._Ma_Loai_Admin != value))
				{
					this.OnMa_Loai_AdminChanging(value);
					this.SendPropertyChanging();
					this._Ma_Loai_Admin = value;
					this.SendPropertyChanged("Ma_Loai_Admin");
					this.OnMa_Loai_AdminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_Loai", DbType="NVarChar(30)")]
		public string Ten_Loai
		{
			get
			{
				return this._Ten_Loai;
			}
			set
			{
				if ((this._Ten_Loai != value))
				{
					this.OnTen_LoaiChanging(value);
					this.SendPropertyChanging();
					this._Ten_Loai = value;
					this.SendPropertyChanged("Ten_Loai");
					this.OnTen_LoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Loaiadmin_Admin", Storage="_Admins", ThisKey="Ma_Loai_Admin", OtherKey="Ma_Loai_Admin")]
		public EntitySet<Admin> Admins
		{
			get
			{
				return this._Admins;
			}
			set
			{
				this._Admins.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Admins(Admin entity)
		{
			this.SendPropertyChanging();
			entity.Loaiadmin = this;
		}
		
		private void detach_Admins(Admin entity)
		{
			this.SendPropertyChanging();
			entity.Loaiadmin = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.loaisanpham")]
	public partial class loaisanpham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Ma_Loai_SP;
		
		private string _Ten_Loai_SP;
		
		private EntitySet<sanpham> _sanphams;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_Loai_SPChanging(int value);
    partial void OnMa_Loai_SPChanged();
    partial void OnTen_Loai_SPChanging(string value);
    partial void OnTen_Loai_SPChanged();
    #endregion
		
		public loaisanpham()
		{
			this._sanphams = new EntitySet<sanpham>(new Action<sanpham>(this.attach_sanphams), new Action<sanpham>(this.detach_sanphams));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_Loai_SP", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Ma_Loai_SP
		{
			get
			{
				return this._Ma_Loai_SP;
			}
			set
			{
				if ((this._Ma_Loai_SP != value))
				{
					this.OnMa_Loai_SPChanging(value);
					this.SendPropertyChanging();
					this._Ma_Loai_SP = value;
					this.SendPropertyChanged("Ma_Loai_SP");
					this.OnMa_Loai_SPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_Loai_SP", DbType="NVarChar(40)")]
		public string Ten_Loai_SP
		{
			get
			{
				return this._Ten_Loai_SP;
			}
			set
			{
				if ((this._Ten_Loai_SP != value))
				{
					this.OnTen_Loai_SPChanging(value);
					this.SendPropertyChanging();
					this._Ten_Loai_SP = value;
					this.SendPropertyChanged("Ten_Loai_SP");
					this.OnTen_Loai_SPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="loaisanpham_sanpham", Storage="_sanphams", ThisKey="Ma_Loai_SP", OtherKey="Ma_Loai_SP")]
		public EntitySet<sanpham> sanphams
		{
			get
			{
				return this._sanphams;
			}
			set
			{
				this._sanphams.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_sanphams(sanpham entity)
		{
			this.SendPropertyChanging();
			entity.loaisanpham = this;
		}
		
		private void detach_sanphams(sanpham entity)
		{
			this.SendPropertyChanging();
			entity.loaisanpham = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nhacungcap")]
	public partial class nhacungcap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Ma_NCC;
		
		private string _Ten_NCC;
		
		private string _Dia_Chi;
		
		private string _SDT;
		
		private EntitySet<phieunhap> _phieunhaps;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_NCCChanging(string value);
    partial void OnMa_NCCChanged();
    partial void OnTen_NCCChanging(string value);
    partial void OnTen_NCCChanged();
    partial void OnDia_ChiChanging(string value);
    partial void OnDia_ChiChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    #endregion
		
		public nhacungcap()
		{
			this._phieunhaps = new EntitySet<phieunhap>(new Action<phieunhap>(this.attach_phieunhaps), new Action<phieunhap>(this.detach_phieunhaps));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_NCC", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Ma_NCC
		{
			get
			{
				return this._Ma_NCC;
			}
			set
			{
				if ((this._Ma_NCC != value))
				{
					this.OnMa_NCCChanging(value);
					this.SendPropertyChanging();
					this._Ma_NCC = value;
					this.SendPropertyChanged("Ma_NCC");
					this.OnMa_NCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_NCC", DbType="NVarChar(30)")]
		public string Ten_NCC
		{
			get
			{
				return this._Ten_NCC;
			}
			set
			{
				if ((this._Ten_NCC != value))
				{
					this.OnTen_NCCChanging(value);
					this.SendPropertyChanging();
					this._Ten_NCC = value;
					this.SendPropertyChanged("Ten_NCC");
					this.OnTen_NCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dia_Chi", DbType="NVarChar(70)")]
		public string Dia_Chi
		{
			get
			{
				return this._Dia_Chi;
			}
			set
			{
				if ((this._Dia_Chi != value))
				{
					this.OnDia_ChiChanging(value);
					this.SendPropertyChanging();
					this._Dia_Chi = value;
					this.SendPropertyChanged("Dia_Chi");
					this.OnDia_ChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(10)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhacungcap_phieunhap", Storage="_phieunhaps", ThisKey="Ma_NCC", OtherKey="Ma_NCC")]
		public EntitySet<phieunhap> phieunhaps
		{
			get
			{
				return this._phieunhaps;
			}
			set
			{
				this._phieunhaps.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_phieunhaps(phieunhap entity)
		{
			this.SendPropertyChanging();
			entity.nhacungcap = this;
		}
		
		private void detach_phieunhaps(phieunhap entity)
		{
			this.SendPropertyChanging();
			entity.nhacungcap = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.phieunhap")]
	public partial class phieunhap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Ma_PN;
		
		private string _Ma_Admin;
		
		private string _Ma_NCC;
		
		private System.Nullable<int> _Ma_SP;
		
		private System.Nullable<byte> _So_Luong;
		
		private EntityRef<Admin> _Admin;
		
		private EntityRef<nhacungcap> _nhacungcap;
		
		private EntityRef<sanpham> _sanpham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_PNChanging(string value);
    partial void OnMa_PNChanged();
    partial void OnMa_AdminChanging(string value);
    partial void OnMa_AdminChanged();
    partial void OnMa_NCCChanging(string value);
    partial void OnMa_NCCChanged();
    partial void OnMa_SPChanging(System.Nullable<int> value);
    partial void OnMa_SPChanged();
    partial void OnSo_LuongChanging(System.Nullable<byte> value);
    partial void OnSo_LuongChanged();
    #endregion
		
		public phieunhap()
		{
			this._Admin = default(EntityRef<Admin>);
			this._nhacungcap = default(EntityRef<nhacungcap>);
			this._sanpham = default(EntityRef<sanpham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_PN", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Ma_PN
		{
			get
			{
				return this._Ma_PN;
			}
			set
			{
				if ((this._Ma_PN != value))
				{
					this.OnMa_PNChanging(value);
					this.SendPropertyChanging();
					this._Ma_PN = value;
					this.SendPropertyChanged("Ma_PN");
					this.OnMa_PNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_Admin", DbType="VarChar(10)")]
		public string Ma_Admin
		{
			get
			{
				return this._Ma_Admin;
			}
			set
			{
				if ((this._Ma_Admin != value))
				{
					if (this._Admin.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMa_AdminChanging(value);
					this.SendPropertyChanging();
					this._Ma_Admin = value;
					this.SendPropertyChanged("Ma_Admin");
					this.OnMa_AdminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_NCC", DbType="VarChar(10)")]
		public string Ma_NCC
		{
			get
			{
				return this._Ma_NCC;
			}
			set
			{
				if ((this._Ma_NCC != value))
				{
					if (this._nhacungcap.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMa_NCCChanging(value);
					this.SendPropertyChanging();
					this._Ma_NCC = value;
					this.SendPropertyChanged("Ma_NCC");
					this.OnMa_NCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_SP", DbType="Int")]
		public System.Nullable<int> Ma_SP
		{
			get
			{
				return this._Ma_SP;
			}
			set
			{
				if ((this._Ma_SP != value))
				{
					if (this._sanpham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMa_SPChanging(value);
					this.SendPropertyChanging();
					this._Ma_SP = value;
					this.SendPropertyChanged("Ma_SP");
					this.OnMa_SPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_So_Luong", DbType="TinyInt")]
		public System.Nullable<byte> So_Luong
		{
			get
			{
				return this._So_Luong;
			}
			set
			{
				if ((this._So_Luong != value))
				{
					this.OnSo_LuongChanging(value);
					this.SendPropertyChanging();
					this._So_Luong = value;
					this.SendPropertyChanged("So_Luong");
					this.OnSo_LuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Admin_phieunhap", Storage="_Admin", ThisKey="Ma_Admin", OtherKey="Ma_Admin", IsForeignKey=true)]
		public Admin Admin
		{
			get
			{
				return this._Admin.Entity;
			}
			set
			{
				Admin previousValue = this._Admin.Entity;
				if (((previousValue != value) 
							|| (this._Admin.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Admin.Entity = null;
						previousValue.phieunhaps.Remove(this);
					}
					this._Admin.Entity = value;
					if ((value != null))
					{
						value.phieunhaps.Add(this);
						this._Ma_Admin = value.Ma_Admin;
					}
					else
					{
						this._Ma_Admin = default(string);
					}
					this.SendPropertyChanged("Admin");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhacungcap_phieunhap", Storage="_nhacungcap", ThisKey="Ma_NCC", OtherKey="Ma_NCC", IsForeignKey=true)]
		public nhacungcap nhacungcap
		{
			get
			{
				return this._nhacungcap.Entity;
			}
			set
			{
				nhacungcap previousValue = this._nhacungcap.Entity;
				if (((previousValue != value) 
							|| (this._nhacungcap.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._nhacungcap.Entity = null;
						previousValue.phieunhaps.Remove(this);
					}
					this._nhacungcap.Entity = value;
					if ((value != null))
					{
						value.phieunhaps.Add(this);
						this._Ma_NCC = value.Ma_NCC;
					}
					else
					{
						this._Ma_NCC = default(string);
					}
					this.SendPropertyChanged("nhacungcap");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="sanpham_phieunhap", Storage="_sanpham", ThisKey="Ma_SP", OtherKey="Ma_SP", IsForeignKey=true)]
		public sanpham sanpham
		{
			get
			{
				return this._sanpham.Entity;
			}
			set
			{
				sanpham previousValue = this._sanpham.Entity;
				if (((previousValue != value) 
							|| (this._sanpham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._sanpham.Entity = null;
						previousValue.phieunhaps.Remove(this);
					}
					this._sanpham.Entity = value;
					if ((value != null))
					{
						value.phieunhaps.Add(this);
						this._Ma_SP = value.Ma_SP;
					}
					else
					{
						this._Ma_SP = default(Nullable<int>);
					}
					this.SendPropertyChanged("sanpham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sanpham")]
	public partial class sanpham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Ma_SP;
		
		private string _Ten_SP;
		
		private System.Nullable<int> _Ma_Loai_SP;
		
		private System.Nullable<int> _Don_Gia;
		
		private string _Hinh_Anh;
		
		private string _Cau_Hinh;
		
		private EntitySet<chitiethoadon> _chitiethoadons;
		
		private EntitySet<phieunhap> _phieunhaps;
		
		private EntityRef<loaisanpham> _loaisanpham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_SPChanging(int value);
    partial void OnMa_SPChanged();
    partial void OnTen_SPChanging(string value);
    partial void OnTen_SPChanged();
    partial void OnMa_Loai_SPChanging(System.Nullable<int> value);
    partial void OnMa_Loai_SPChanged();
    partial void OnDon_GiaChanging(System.Nullable<int> value);
    partial void OnDon_GiaChanged();
    partial void OnHinh_AnhChanging(string value);
    partial void OnHinh_AnhChanged();
    partial void OnCau_HinhChanging(string value);
    partial void OnCau_HinhChanged();
    #endregion
		
		public sanpham()
		{
			this._chitiethoadons = new EntitySet<chitiethoadon>(new Action<chitiethoadon>(this.attach_chitiethoadons), new Action<chitiethoadon>(this.detach_chitiethoadons));
			this._phieunhaps = new EntitySet<phieunhap>(new Action<phieunhap>(this.attach_phieunhaps), new Action<phieunhap>(this.detach_phieunhaps));
			this._loaisanpham = default(EntityRef<loaisanpham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_SP", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Ma_SP
		{
			get
			{
				return this._Ma_SP;
			}
			set
			{
				if ((this._Ma_SP != value))
				{
					this.OnMa_SPChanging(value);
					this.SendPropertyChanging();
					this._Ma_SP = value;
					this.SendPropertyChanged("Ma_SP");
					this.OnMa_SPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_SP", DbType="NVarChar(40)")]
		public string Ten_SP
		{
			get
			{
				return this._Ten_SP;
			}
			set
			{
				if ((this._Ten_SP != value))
				{
					this.OnTen_SPChanging(value);
					this.SendPropertyChanging();
					this._Ten_SP = value;
					this.SendPropertyChanged("Ten_SP");
					this.OnTen_SPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_Loai_SP", DbType="Int")]
		public System.Nullable<int> Ma_Loai_SP
		{
			get
			{
				return this._Ma_Loai_SP;
			}
			set
			{
				if ((this._Ma_Loai_SP != value))
				{
					if (this._loaisanpham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMa_Loai_SPChanging(value);
					this.SendPropertyChanging();
					this._Ma_Loai_SP = value;
					this.SendPropertyChanged("Ma_Loai_SP");
					this.OnMa_Loai_SPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Don_Gia", DbType="Int")]
		public System.Nullable<int> Don_Gia
		{
			get
			{
				return this._Don_Gia;
			}
			set
			{
				if ((this._Don_Gia != value))
				{
					this.OnDon_GiaChanging(value);
					this.SendPropertyChanging();
					this._Don_Gia = value;
					this.SendPropertyChanged("Don_Gia");
					this.OnDon_GiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hinh_Anh", DbType="VarChar(70)")]
		public string Hinh_Anh
		{
			get
			{
				return this._Hinh_Anh;
			}
			set
			{
				if ((this._Hinh_Anh != value))
				{
					this.OnHinh_AnhChanging(value);
					this.SendPropertyChanging();
					this._Hinh_Anh = value;
					this.SendPropertyChanged("Hinh_Anh");
					this.OnHinh_AnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cau_Hinh", DbType="NVarChar(100)")]
		public string Cau_Hinh
		{
			get
			{
				return this._Cau_Hinh;
			}
			set
			{
				if ((this._Cau_Hinh != value))
				{
					this.OnCau_HinhChanging(value);
					this.SendPropertyChanging();
					this._Cau_Hinh = value;
					this.SendPropertyChanged("Cau_Hinh");
					this.OnCau_HinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="sanpham_chitiethoadon", Storage="_chitiethoadons", ThisKey="Ma_SP", OtherKey="Ma_SP")]
		public EntitySet<chitiethoadon> chitiethoadons
		{
			get
			{
				return this._chitiethoadons;
			}
			set
			{
				this._chitiethoadons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="sanpham_phieunhap", Storage="_phieunhaps", ThisKey="Ma_SP", OtherKey="Ma_SP")]
		public EntitySet<phieunhap> phieunhaps
		{
			get
			{
				return this._phieunhaps;
			}
			set
			{
				this._phieunhaps.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="loaisanpham_sanpham", Storage="_loaisanpham", ThisKey="Ma_Loai_SP", OtherKey="Ma_Loai_SP", IsForeignKey=true)]
		public loaisanpham loaisanpham
		{
			get
			{
				return this._loaisanpham.Entity;
			}
			set
			{
				loaisanpham previousValue = this._loaisanpham.Entity;
				if (((previousValue != value) 
							|| (this._loaisanpham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._loaisanpham.Entity = null;
						previousValue.sanphams.Remove(this);
					}
					this._loaisanpham.Entity = value;
					if ((value != null))
					{
						value.sanphams.Add(this);
						this._Ma_Loai_SP = value.Ma_Loai_SP;
					}
					else
					{
						this._Ma_Loai_SP = default(Nullable<int>);
					}
					this.SendPropertyChanged("loaisanpham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_chitiethoadons(chitiethoadon entity)
		{
			this.SendPropertyChanging();
			entity.sanpham = this;
		}
		
		private void detach_chitiethoadons(chitiethoadon entity)
		{
			this.SendPropertyChanging();
			entity.sanpham = null;
		}
		
		private void attach_phieunhaps(phieunhap entity)
		{
			this.SendPropertyChanging();
			entity.sanpham = this;
		}
		
		private void detach_phieunhaps(phieunhap entity)
		{
			this.SendPropertyChanging();
			entity.sanpham = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.taikhoan")]
	public partial class taikhoan
	{
		
		private string _Ten_DN;
		
		private string _Ma_Admin;
		
		private string _MK_DN;
		
		public taikhoan()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_DN", DbType="VarChar(25)")]
		public string Ten_DN
		{
			get
			{
				return this._Ten_DN;
			}
			set
			{
				if ((this._Ten_DN != value))
				{
					this._Ten_DN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_Admin", DbType="VarChar(10)")]
		public string Ma_Admin
		{
			get
			{
				return this._Ma_Admin;
			}
			set
			{
				if ((this._Ma_Admin != value))
				{
					this._Ma_Admin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MK_DN", DbType="VarChar(25)")]
		public string MK_DN
		{
			get
			{
				return this._MK_DN;
			}
			set
			{
				if ((this._MK_DN != value))
				{
					this._MK_DN = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
